"""creer tables articles fournisseurs entrees sorties

Revision ID: 0340cf32b856
Revises: f15b3fc87863
Create Date: 2026-08-31 14:10:01.542721

"""
from datetime import date

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0340cf32b856'
down_revision = 'f15b3fc87863'
branch_labels = None
depends_on = None


# --- Données initiales : mêmes articles et mouvements que l'ancienne
# démo en mémoire (apps/gtc_data.py). Note : les deux anciennes listes
# statiques (MOUVEMENTS et HISTORIQUE) se contredisaient pour un article
# (dates/quantités différentes) ; on reprend ici HISTORIQUE, qui est
# celle dont les soldes correspondent bien aux quantités actuelles.
ARTICLES_INITIAUX = [
    {"nom": "Rame de papier A4", "reference": "REF-0021", "quantite": 5, "seuil": 10,
     "statut": "Alerte", "sage_quantite": 5, "dernier_mouvement": "22/08/2026"},
    {"nom": "Cartouche imprimante", "reference": "REF-0045", "quantite": 50, "seuil": 20,
     "statut": "OK", "sage_quantite": 50, "dernier_mouvement": "20/08/2026"},
    {"nom": "Classeur A4", "reference": "REF-0102", "quantite": 8, "seuil": 15,
     "statut": "Alerte", "sage_quantite": 11, "dernier_mouvement": "21/08/2026"},
    {"nom": "Chaise bureau (modèle X)", "reference": "REF-0230", "quantite": 14, "seuil": 2,
     "statut": "Dormant", "sage_quantite": 14, "dernier_mouvement": "—"},
    {"nom": "Stylo bille bleu (boîte)", "reference": "REF-0011", "quantite": 96, "seuil": 30,
     "statut": "OK", "sage_quantite": 90, "dernier_mouvement": "18/08/2026"},
]

FOURNISSEURS_INITIAUX = [
    {"nom": "Papeterie Générale SARL", "contact": "contact@papgen.example"},
    {"nom": "Bureau Plus Distribution", "contact": "commandes@bureauplus.example"},
]

# (reference_article, date, quantite, reference_document, type_document_si_sortie)
ENTREES_INITIALES = [
    ("REF-0021", date(2026, 8, 10), 20, "BR-2026-0110"),
    ("REF-0045", date(2026, 8, 5), 30, "BR-2026-0098"),
    ("REF-0102", date(2026, 8, 1), 13, "BR-2026-0075"),
    ("REF-0230", date(2026, 5, 15), 14, "BR-2026-0033"),
    ("REF-0011", date(2026, 8, 2), 40, "BR-2026-0091"),
]
SORTIES_INITIALES = [
    ("REF-0021", date(2026, 8, 22), 15, "BL-2026-0090", "Bon de livraison"),
    ("REF-0021", date(2026, 7, 28), 10, "BC-2026-0175", "Bordereau de route"),
    ("REF-0045", date(2026, 8, 20), 10, "BC-2026-0212", "Bordereau de route"),
    ("REF-0102", date(2026, 8, 21), 5, "BL-2026-0087", "Bon de livraison"),
    ("REF-0011", date(2026, 8, 18), 4, "BL-2026-0080", "Bon de livraison"),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('seuil', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('sage_quantite', sa.Integer(), nullable=True),
    sa.Column('dernier_mouvement', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_reference'), ['reference'], unique=True)

    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fournisseurs_nom'), ['nom'], unique=True)

    op.create_table('entrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Données initiales ---
    conn = op.get_bind()

    articles_table = sa.table(
        'articles',
        sa.column('id', sa.Integer), sa.column('nom', sa.String),
        sa.column('reference', sa.String), sa.column('quantite', sa.Integer),
        sa.column('seuil', sa.Integer), sa.column('statut', sa.String),
        sa.column('sage_quantite', sa.Integer), sa.column('dernier_mouvement', sa.String),
    )
    fournisseurs_table = sa.table(
        'fournisseurs', sa.column('id', sa.Integer),
        sa.column('nom', sa.String), sa.column('contact', sa.String),
    )
    entrees_table = sa.table(
        'entrees', sa.column('article_id', sa.Integer), sa.column('date', sa.Date),
        sa.column('quantite', sa.Integer), sa.column('fournisseur', sa.String),
        sa.column('reference', sa.String), sa.column('utilisateur_id', sa.Integer),
    )
    sorties_table = sa.table(
        'sorties', sa.column('article_id', sa.Integer), sa.column('date', sa.Date),
        sa.column('quantite', sa.Integer), sa.column('type_document', sa.String),
        sa.column('reference', sa.String), sa.column('utilisateur_id', sa.Integer),
    )

    op.bulk_insert(articles_table, ARTICLES_INITIAUX)
    op.bulk_insert(fournisseurs_table, FOURNISSEURS_INITIAUX)

    # Correspondance référence -> id, généré par la base (pas fiable de
    # deviner l'auto-incrément à l'avance).
    articles_par_ref = {
        row.reference: row.id
        for row in conn.execute(sa.text("SELECT id, reference FROM articles"))
    }
    fournisseur_id = conn.execute(
        sa.text("SELECT id FROM fournisseurs ORDER BY id LIMIT 1")
    ).scalar()
    jdupont_id = conn.execute(
        sa.text("SELECT id FROM utilisateurs WHERE identifiant = 'j.dupont'")
    ).scalar()

    op.bulk_insert(entrees_table, [
        {
            "article_id": articles_par_ref[ref], "date": d, "quantite": qte,
            "fournisseur": fournisseur_id and FOURNISSEURS_INITIAUX[0]["nom"],
            "reference": reference_doc, "utilisateur_id": jdupont_id,
        }
        for ref, d, qte, reference_doc in ENTREES_INITIALES
    ])
    op.bulk_insert(sorties_table, [
        {
            "article_id": articles_par_ref[ref], "date": d, "quantite": qte,
            "reference": reference_doc, "type_document": type_doc,
            "utilisateur_id": jdupont_id,
        }
        for ref, d, qte, reference_doc, type_doc in SORTIES_INITIALES
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorties')
    op.drop_table('entrees')
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fournisseurs_nom'))

    op.drop_table('fournisseurs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_reference'))

    op.drop_table('articles')
    # ### end Alembic commands ###
