"""creer tables articles fournisseurs entrees sorties

Revision ID: 0340cf32b856
Revises: f15b3fc87863
Create Date: 2026-08-31 14:10:01.542721

"""
from datetime import date

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0340cf32b856'
down_revision = 'f15b3fc87863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('seuil', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('sage_quantite', sa.Integer(), nullable=True),
    sa.Column('dernier_mouvement', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_reference'), ['reference'], unique=True)

    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fournisseurs_nom'), ['nom'], unique=True)

    op.create_table('entrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Pas de données initiales : les articles, fournisseurs et mouvements
    # de démonstration (papeterie) ne correspondaient pas à l'activité de
    # GTC sarl (denrées alimentaires) ; voir la migration e8a1c4d2b9f0
    # qui les retire des bases déjà migrées.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorties')
    op.drop_table('entrees')
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fournisseurs_nom'))

    op.drop_table('fournisseurs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_reference'))

    op.drop_table('articles')
    # ### end Alembic commands ###
