"""add tentatives_connexion table (rate limiting)

Revision ID: 165304ad9c99
Revises: 276120d6d4b9
Create Date: 2026-08-26 15:22:21.480476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165304ad9c99'
down_revision = '276120d6d4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentatives_connexion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=160), nullable=False),
    sa.Column('echecs', sa.Integer(), nullable=False),
    sa.Column('bloque_jusqua', sa.DateTime(), nullable=True),
    sa.Column('derniere_tentative', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentatives_connexion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentatives_connexion_cle'), ['cle'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tentatives_connexion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentatives_connexion_cle'))

    op.drop_table('tentatives_connexion')
    # ### end Alembic commands ###
