"""create utilisateurs table

Revision ID: 276120d6d4b9
Revises: 
Create Date: 2026-08-26 09:54:13.306682

"""
from alembic import op
import sqlalchemy as sa

from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '276120d6d4b9'
down_revision = None
branch_labels = None
depends_on = None


# Table utilitaire pour l'insertion des données initiales (upgrade) /
# leur identification lors du nettoyage (downgrade).
utilisateurs_table = sa.table(
    'utilisateurs',
    sa.column('nom', sa.String),
    sa.column('identifiant', sa.String),
    sa.column('mot_de_passe_hash', sa.String),
    sa.column('role', sa.String),
    sa.column('actif', sa.Boolean),
    sa.column('derniere_connexion', sa.String),
)

# Comptes de démonstration existants avant la mise en place de la base.
COMPTES_INITIAUX = [
    {"nom": "Jean Dupont", "identifiant": "j.dupont", "role": "Gestionnaire de stock",
     "mot_de_passe": "Dupont@2026", "actif": True, "derniere_connexion": "24/08/2026 — 08:03"},
    {"nom": "Marie Kouam", "identifiant": "m.kouam", "role": "Comptable",
     "mot_de_passe": "Kouam@2026", "actif": True, "derniere_connexion": "23/08/2026 — 17:45"},
    {"nom": "Paul Meka", "identifiant": "p.meka", "role": "Administrateur",
     "mot_de_passe": "Meka@2026", "actif": True, "derniere_connexion": "24/08/2026 — 07:00"},
    {"nom": "Sara Nkolo", "identifiant": "s.nkolo", "role": "Gestionnaire de stock",
     "mot_de_passe": "Nkolo@2026", "actif": False, "derniere_connexion": "02/06/2026 — 11:20"},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('identifiant', sa.String(length=80), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateurs_identifiant'), ['identifiant'], unique=True)

    # ### end Alembic commands ###

    # --- Données initiales : comptes de démonstration ---
    op.bulk_insert(utilisateurs_table, [
        {
            "nom": compte["nom"],
            "identifiant": compte["identifiant"],
            "mot_de_passe_hash": generate_password_hash(compte["mot_de_passe"]),
            "role": compte["role"],
            "actif": compte["actif"],
            "derniere_connexion": compte["derniere_connexion"],
        }
        for compte in COMPTES_INITIAUX
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateurs_identifiant'))

    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
