"""creer table journal_activite (audit log)

Revision ID: 2e0684712b73
Revises: 8ab4cbdfcfb7
Create Date: 2026-08-31 17:04:36.728300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0684712b73'
down_revision = '8ab4cbdfcfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('identifiant', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_activite')
    # ### end Alembic commands ###
