"""ajouter email_alertes sur magasins

Revision ID: 6cf9ceca7dcb
Revises: c85378237d56
Create Date: 2026-08-31 17:53:20.450605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf9ceca7dcb'
down_revision = 'c85378237d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_alertes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # Adresses d'alerte de démonstration pour les 2 magasins fictifs
    # (adresses .example, non routables — à remplacer par les vraies
    # boîtes / listes de diffusion en production).
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE magasins SET email_alertes = :e WHERE nom = 'Magasin Principal'"
    ), {"e": "stock.principal@gtc.example"})
    conn.execute(sa.text(
        "UPDATE magasins SET email_alertes = :e WHERE nom = 'Magasin Secondaire'"
    ), {"e": "stock.secondaire@gtc.example"})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.drop_column('email_alertes')

    # ### end Alembic commands ###
