"""ajouter fournisseur habituel sur article

Revision ID: 8ab4cbdfcfb7
Revises: 7d2038394086
Create Date: 2026-08-31 16:21:13.623025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab4cbdfcfb7'
down_revision = '7d2038394086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_articles_fournisseur_id', 'fournisseurs', ['fournisseur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_fournisseur_id', type_='foreignkey')
        batch_op.drop_column('fournisseur_id')

    # ### end Alembic commands ###
