"""ajouter archive (suppression douce) sur article

Revision ID: ac38a8d416d5
Revises: 6cf9ceca7dcb
Create Date: 2026-09-01 15:54:14.383823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac38a8d416d5'
down_revision = '6cf9ceca7dcb'
branch_labels = None
depends_on = None


def upgrade():
    # Suppression douce des articles : un article archivé est conservé en
    # base (avec son historique de mouvements) mais retiré des vues
    # opérationnelles. server_default='0' -> les articles existants sont
    # tous marqués non archivés.
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('archive')

    # ### end Alembic commands ###
