"""creer table magasins et rattacher utilisateurs/articles

Revision ID: c85378237d56
Revises: 2e0684712b73
Create Date: 2026-08-31 17:23:55.599079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85378237d56'
down_revision = '2e0684712b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magasins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magasins_nom'), ['nom'], unique=True)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magasin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_articles_magasin_id', 'magasins', ['magasin_id'], ['id'])

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magasin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_utilisateurs_magasin_id', 'magasins', ['magasin_id'], ['id'])

    # ### end Alembic commands ###

    # --- Données initiales : 2 magasins de démo, données existantes réparties ---
    conn = op.get_bind()

    magasins_table = sa.table('magasins', sa.column('id', sa.Integer),
                               sa.column('nom', sa.String), sa.column('adresse', sa.String))
    op.bulk_insert(magasins_table, [
        {"nom": "Magasin Principal", "adresse": "Zone industrielle, entrepôt A"},
        {"nom": "Magasin Secondaire", "adresse": "Zone industrielle, entrepôt B"},
    ])
    principal_id, secondaire_id = [
        row.id for row in conn.execute(sa.text(
            "SELECT id FROM magasins ORDER BY id"
        ))
    ]

    # Gestionnaires de stock : un par magasin de démo. Comptable/Administrateur
    # restent sans magasin (NULL) — ils voient tout (voir ROLES_TOUS_MAGASINS).
    conn.execute(sa.text(
        "UPDATE utilisateurs SET magasin_id = :m WHERE identifiant = 'j.dupont'"
    ), {"m": principal_id})
    conn.execute(sa.text(
        "UPDATE utilisateurs SET magasin_id = :m WHERE identifiant = 's.nkolo'"
    ), {"m": secondaire_id})

    # Articles répartis sur les 2 magasins de démo (par référence, pour ne
    # pas dépendre d'un ordre d'auto-incrément).
    articles_principal = ['REF-0021', 'REF-0045', 'REF-0102']
    articles_secondaire = ['REF-0230', 'REF-0011']
    for ref in articles_principal:
        conn.execute(sa.text(
            "UPDATE articles SET magasin_id = :m WHERE reference = :r"
        ), {"m": principal_id, "r": ref})
    for ref in articles_secondaire:
        conn.execute(sa.text(
            "UPDATE articles SET magasin_id = :m WHERE reference = :r"
        ), {"m": secondaire_id, "r": ref})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_utilisateurs_magasin_id', type_='foreignkey')
        batch_op.drop_column('magasin_id')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_magasin_id', type_='foreignkey')
        batch_op.drop_column('magasin_id')

    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magasins_nom'))

    op.drop_table('magasins')
    # ### end Alembic commands ###
