"""creer table alertes

Revision ID: fb73d9c76e4a
Revises: ac38a8d416d5
Create Date: 2026-09-12 00:17:05.964403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb73d9c76e4a'
down_revision = 'ac38a8d416d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.Column('traitee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('magasin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Pas de données initiales : les alertes de démonstration (Classeur A4,
    # Stylo bille, Rame de papier A4…) ne correspondaient pas à l'activité
    # de GTC sarl (denrées alimentaires) ; voir la migration e8a1c4d2b9f0
    # qui les retire des bases déjà migrées.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertes')
    # ### end Alembic commands ###
