"""creer table alertes

Revision ID: fb73d9c76e4a
Revises: ac38a8d416d5
Create Date: 2026-09-12 00:17:05.964403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb73d9c76e4a'
down_revision = 'ac38a8d416d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.Column('traitee', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('magasin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Données initiales : les 4 alertes de démonstration qui vivaient
    # jusqu'ici en dur dans apps/gtc_data.py (ALERTES), désormais en base.
    # Chaque alerte est rattachée au magasin de l'article qu'elle cite
    # (REF-0021/REF-0102 -> Magasin Principal, REF-0011 -> Magasin
    # Secondaire — voir la migration c85378237d56).
    conn = op.get_bind()
    magasin_de_ref = {
        row.reference: row.magasin_id
        for row in conn.execute(sa.text(
            "SELECT reference, magasin_id FROM articles "
            "WHERE reference IN ('REF-0021', 'REF-0102', 'REF-0011')"
        ))
    }

    alertes_table = sa.table(
        'alertes',
        sa.column('titre', sa.String), sa.column('detail', sa.String),
        sa.column('date', sa.String), sa.column('type', sa.String),
        sa.column('icone', sa.String), sa.column('traitee', sa.Boolean),
        sa.column('magasin_id', sa.Integer),
    )
    op.bulk_insert(alertes_table, [
        {
            "titre": "Écart de rapprochement — Classeur A4",
            "detail": "Quantité application : 8 — Quantité Sage 100 : 11 (écart de -3)",
            "date": "24/08/2026 à 07:12", "type": "ecart",
            "icone": "bi-shield-exclamation", "traitee": False,
            "magasin_id": magasin_de_ref.get('REF-0102'),
        },
        {
            "titre": "Écart de rapprochement — Stylo bille bleu (boîte)",
            "detail": "Quantité application : 96 — Quantité Sage 100 : 90 (écart de +6)",
            "date": "24/08/2026 à 07:12", "type": "ecart",
            "icone": "bi-shield-exclamation", "traitee": False,
            "magasin_id": magasin_de_ref.get('REF-0011'),
        },
        {
            "titre": "Seuil critique atteint — Rame de papier A4",
            "detail": "Quantité actuelle : 5 — Seuil d'alerte : 10",
            "date": "22/08/2026 à 16:40", "type": "seuil",
            "icone": "bi-exclamation-triangle", "traitee": True,
            "magasin_id": magasin_de_ref.get('REF-0021'),
        },
        {
            "titre": "Seuil critique atteint — Classeur A4",
            "detail": "Quantité actuelle : 8 — Seuil d'alerte : 15",
            "date": "21/08/2026 à 09:05", "type": "seuil",
            "icone": "bi-exclamation-triangle", "traitee": False,
            "magasin_id": magasin_de_ref.get('REF-0102'),
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertes')
    # ### end Alembic commands ###
